services:
  nginx:
    build:
      context: .
      dockerfile: ./infra/production/nginx/Dockerfile
    ports:
      - 3333:80
    volumes:
      - ./laravel:/var/www/html
      - ./infra/production/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
  app:
    build: ./infra/production/php
    volumes:
      - ./laravel:/var/www/html
  db:
    build: ./infra/production/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "6666:3306"

volumes:
  db-store:
